import Head from "next/head";
import { FC, ReactNode } from "react";

type Props = {
  title: string;
  children: ReactNode;
};

export const Layout: FC<Props> = ({ title = "T3 Stack", children }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
        <header></header>
        <main>{children}</main>
        <footer></footer>
      </div>
    </>
  );
};
